---
title: "DenNea PCA"
author: "Sarah Johnson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/global/scratch/p2p3/pl1_moorjani/sarahj32/denisova_dating")
rm(list = ls())

# set plotting settings and variables
theme_set(theme_bw() +
            theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
            theme(axis.text = element_text(size = 10)))

library(tidyverse)
```

Read in PCA for one of the chromosomes
```{r}
evec <- read.table("testing/simulate_papuans/denNea_pca_14.evec")
exp <- read.table("testing/simulate_papuans/denNea_pca_14.evec", comment.char = "") %>% colnames()
exp <- gsub("X", "", exp)[2:length(exp)]


colnames(evec) <- c("ind", paste0("PC_", 1:10), "pop")
evec <- separate(evec, ind, into = c("pop", "rep"), remove = F, sep = "_") %>% select(-rep)

pc12 <- ggplot(evec, aes(x = PC_1, y = PC_2, color = pop)) +
  geom_point() +
  labs(x = paste0("PC1, % explained = ", exp[1]), y = paste0("PC2, % explained = ", exp[2]))
plot(pc12)

pdf("testing/simulate_papuans/DenNea_PCA.pdf", height = 4, width = 5)
plot(pc12)
dev.off()

ggplot(evec, aes(x = PC_3, y = PC_4, color = pop)) +
  geom_point()

ggplot(evec, aes(x = PC_5, y = PC_6, color = pop)) +
  geom_point()
```

